# Generated by Django 2.2 on 2019-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='londonweather',
            name='icon',
        ),
    ]
